export interface Country {
  name: string;
  flag: string;
  dial_code: string;
}

// A comprehensive list of all countries with flags and dial codes
export const countries: Country[] = [
  { name: "Afghanistan", flag: "https://flagcdn.com/af.svg", dial_code: "+93" },
  { name: "Albania", flag: "https://flagcdn.com/al.svg", dial_code: "+355" },
  { name: "Algeria", flag: "https://flagcdn.com/dz.svg", dial_code: "+213" },
  { name: "American Samoa", flag: "https://flagcdn.com/as.svg", dial_code: "+1684" },
  { name: "Andorra", flag: "https://flagcdn.com/ad.svg", dial_code: "+376" },
  { name: "Angola", flag: "https://flagcdn.com/ao.svg", dial_code: "+244" },
  { name: "Anguilla", flag: "https://flagcdn.com/ai.svg", dial_code: "+1264" },
  { name: "Antarctica", flag: "https://flagcdn.com/aq.svg", dial_code: "+672" },
  { name: "Antigua and Barbuda", flag: "https://flagcdn.com/ag.svg", dial_code: "+1268" },
  { name: "Argentina", flag: "https://flagcdn.com/ar.svg", dial_code: "+54" },
  { name: "Armenia", flag: "https://flagcdn.com/am.svg", dial_code: "+374" },
  { name: "Aruba", flag: "https://flagcdn.com/aw.svg", dial_code: "+297" },
  { name: "Australia", flag: "https://flagcdn.com/au.svg", dial_code: "+61" },
  { name: "Austria", flag: "https://flagcdn.com/at.svg", dial_code: "+43" },
  { name: "Azerbaijan", flag: "https://flagcdn.com/az.svg", dial_code: "+994" },
  { name: "Bahamas", flag: "https://flagcdn.com/bs.svg", dial_code: "+1242" },
  { name: "Bahrain", flag: "https://flagcdn.com/bh.svg", dial_code: "+973" },
  { name: "Bangladesh", flag: "https://flagcdn.com/bd.svg", dial_code: "+880" },
  { name: "Barbados", flag: "https://flagcdn.com/bb.svg", dial_code: "+1246" },
  { name: "Belarus", flag: "https://flagcdn.com/by.svg", dial_code: "+375" },
  { name: "Belgium", flag: "https://flagcdn.com/be.svg", dial_code: "+32" },
  { name: "Belize", flag: "https://flagcdn.com/bz.svg", dial_code: "+501" },
  { name: "Benin", flag: "https://flagcdn.com/bj.svg", dial_code: "+229" },
  { name: "Bermuda", flag: "https://flagcdn.com/bm.svg", dial_code: "+1441" },
  { name: "Bhutan", flag: "https://flagcdn.com/bt.svg", dial_code: "+975" },
  { name: "Bolivia", flag: "https://flagcdn.com/bo.svg", dial_code: "+591" },
  { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/ba.svg", dial_code: "+387" },
  { name: "Botswana", flag: "https://flagcdn.com/bw.svg", dial_code: "+267" },
  { name: "Brazil", flag: "https://flagcdn.com/br.svg", dial_code: "+55" },
  { name: "British Indian Ocean Territory", flag: "https://flagcdn.com/io.svg", dial_code: "+246" },
  { name: "British Virgin Islands", flag: "https://flagcdn.com/vg.svg", dial_code: "+1284" },
  { name: "Brunei", flag: "https://flagcdn.com/bn.svg", dial_code: "+673" },
  { name: "Bulgaria", flag: "https://flagcdn.com/bg.svg", dial_code: "+359" },
  { name: "Burkina Faso", flag: "https://flagcdn.com/bf.svg", dial_code: "+226" },
  { name: "Burundi", flag: "https://flagcdn.com/bi.svg", dial_code: "+257" },
  { name: "Cambodia", flag: "https://flagcdn.com/kh.svg", dial_code: "+855" },
  { name: "Cameroon", flag: "https://flagcdn.com/cm.svg", dial_code: "+237" },
  { name: "Canada", flag: "https://flagcdn.com/ca.svg", dial_code: "+1" },
  { name: "Cape Verde", flag: "https://flagcdn.com/cv.svg", dial_code: "+238" },
  { name: "Cayman Islands", flag: "https://flagcdn.com/ky.svg", dial_code: "+1345" },
  { name: "Central African Republic", flag: "https://flagcdn.com/cf.svg", dial_code: "+236" },
  { name: "Chad", flag: "https://flagcdn.com/td.svg", dial_code: "+235" },
  { name: "Chile", flag: "https://flagcdn.com/cl.svg", dial_code: "+56" },
  { name: "China", flag: "https://flagcdn.com/cn.svg", dial_code: "+86" },
  { name: "Christmas Island", flag: "https://flagcdn.com/cx.svg", dial_code: "+61" },
  { name: "Cocos (Keeling) Islands", flag: "https://flagcdn.com/cc.svg", dial_code: "+61" },
  { name: "Colombia", flag: "https://flagcdn.com/co.svg", dial_code: "+57" },
  { name: "Comoros", flag: "https://flagcdn.com/km.svg", dial_code: "+269" },
  { name: "Cook Islands", flag: "https://flagcdn.com/ck.svg", dial_code: "+682" },
  { name: "Costa Rica", flag: "https://flagcdn.com/cr.svg", dial_code: "+506" },
  { name: "Croatia", flag: "https://flagcdn.com/hr.svg", dial_code: "+385" },
  { name: "Cuba", flag: "https://flagcdn.com/cu.svg", dial_code: "+53" },
  { name: "Curacao", flag: "https://flagcdn.com/cw.svg", dial_code: "+599" },
  { name: "Cyprus", flag: "https://flagcdn.com/cy.svg", dial_code: "+357" },
  { name: "Czech Republic", flag: "https://flagcdn.com/cz.svg", dial_code: "+420" },
  { name: "Democratic Republic of the Congo", flag: "https://flagcdn.com/cd.svg", dial_code: "+243" },
  { name: "Denmark", flag: "https://flagcdn.com/dk.svg", dial_code: "+45" },
  { name: "Djibouti", flag: "https://flagcdn.com/dj.svg", dial_code: "+253" },
  { name: "Dominica", flag: "https://flagcdn.com/dm.svg", dial_code: "+1767" },
  { name: "Dominican Republic", flag: "https://flagcdn.com/do.svg", dial_code: "+1" },
  { name: "Ecuador", flag: "https://flagcdn.com/ec.svg", dial_code: "+593" },
  { name: "Egypt", flag: "https://flagcdn.com/eg.svg", dial_code: "+20" },
  { name: "El Salvador", flag: "https://flagcdn.com/sv.svg", dial_code: "+503" },
  { name: "Equatorial Guinea", flag: "https://flagcdn.com/gq.svg", dial_code: "+240" },
  { name: "Eritrea", flag: "https://flagcdn.com/er.svg", dial_code: "+291" },
  { name: "Estonia", flag: "https://flagcdn.com/ee.svg", dial_code: "+372" },
  { name: "Ethiopia", flag: "https://flagcdn.com/et.svg", dial_code: "+251" },
  { name: "Falkland Islands", flag: "https://flagcdn.com/fk.svg", dial_code: "+500" },
  { name: "Faroe Islands", flag: "https://flagcdn.com/fo.svg", dial_code: "+298" },
  { name: "Fiji", flag: "https://flagcdn.com/fj.svg", dial_code: "+679" },
  { name: "Finland", flag: "https://flagcdn.com/fi.svg", dial_code: "+358" },
  { name: "France", flag: "https://flagcdn.com/fr.svg", dial_code: "+33" },
  { name: "French Guiana", flag: "https://flagcdn.com/gf.svg", dial_code: "+594" },
  { name: "French Polynesia", flag: "https://flagcdn.com/pf.svg", dial_code: "+689" },
  { name: "Gabon", flag: "https://flagcdn.com/ga.svg", dial_code: "+241" },
  { name: "Gambia", flag: "https://flagcdn.com/gm.svg", dial_code: "+220" },
  { name: "Georgia", flag: "https://flagcdn.com/ge.svg", dial_code: "+995" },
  { name: "Germany", flag: "https://flagcdn.com/de.svg", dial_code: "+49" },
  { name: "Ghana", flag: "https://flagcdn.com/gh.svg", dial_code: "+233" },
  { name: "Gibraltar", flag: "https://flagcdn.com/gi.svg", dial_code: "+350" },
  { name: "Greece", flag: "https://flagcdn.com/gr.svg", dial_code: "+30" },
  { name: "Greenland", flag: "https://flagcdn.com/gl.svg", dial_code: "+299" },
  { name: "Grenada", flag: "https://flagcdn.com/gd.svg", dial_code: "+1473" },
  { name: "Guadeloupe", flag: "https://flagcdn.com/gp.svg", dial_code: "+590" },
  { name: "Guam", flag: "https://flagcdn.com/gu.svg", dial_code: "+1671" },
  { name: "Guatemala", flag: "https://flagcdn.com/gt.svg", dial_code: "+502" },
  { name: "Guernsey", flag: "https://flagcdn.com/gg.svg", dial_code: "+44" },
  { name: "Guinea", flag: "https://flagcdn.com/gn.svg", dial_code: "+224" },
  { name: "Guinea-Bissau", flag: "https://flagcdn.com/gw.svg", dial_code: "+245" },
  { name: "Guyana", flag: "https://flagcdn.com/gy.svg", dial_code: "+592" },
  { name: "Haiti", flag: "https://flagcdn.com/ht.svg", dial_code: "+509" },
  { name: "Honduras", flag: "https://flagcdn.com/hn.svg", dial_code: "+504" },
  { name: "Hong Kong", flag: "https://flagcdn.com/hk.svg", dial_code: "+852" },
  { name: "Hungary", flag: "https://flagcdn.com/hu.svg", dial_code: "+36" },
  { name: "Iceland", flag: "https://flagcdn.com/is.svg", dial_code: "+354" },
  { name: "India", flag: "https://flagcdn.com/in.svg", dial_code: "+91" },
  { name: "Indonesia", flag: "https://flagcdn.com/id.svg", dial_code: "+62" },
  { name: "Iran", flag: "https://flagcdn.com/ir.svg", dial_code: "+98" },
  { name: "Iraq", flag: "https://flagcdn.com/iq.svg", dial_code: "+964" },
  { name: "Ireland", flag: "https://flagcdn.com/ie.svg", dial_code: "+353" },
  { name: "Isle of Man", flag: "https://flagcdn.com/im.svg", dial_code: "+44" },
  { name: "Israel", flag: "https://flagcdn.com/il.svg", dial_code: "+972" },
  { name: "Italy", flag: "https://flagcdn.com/it.svg", dial_code: "+39" },
  { name: "Ivory Coast", flag: "https://flagcdn.com/ci.svg", dial_code: "+225" },
  { name: "Jamaica", flag: "https://flagcdn.com/jm.svg", dial_code: "+1876" },
  { name: "Japan", flag: "https://flagcdn.com/jp.svg", dial_code: "+81" },
  { name: "Jersey", flag: "https://flagcdn.com/je.svg", dial_code: "+44" },
  { name: "Jordan", flag: "https://flagcdn.com/jo.svg", dial_code: "+962" },
  { name: "Kazakhstan", flag: "https://flagcdn.com/kz.svg", dial_code: "+7" },
  { name: "Kenya", flag: "https://flagcdn.com/ke.svg", dial_code: "+254" },
  { name: "Kiribati", flag: "https://flagcdn.com/ki.svg", dial_code: "+686" },
  { name: "Kosovo", flag: "https://flagcdn.com/xk.svg", dial_code: "+383" },
  { name: "Kuwait", flag: "https://flagcdn.com/kw.svg", dial_code: "+965" },
  { name: "Kyrgyzstan", flag: "https://flagcdn.com/kg.svg", dial_code: "+996" },
  { name: "Laos", flag: "https://flagcdn.com/la.svg", dial_code: "+856" },
  { name: "Latvia", flag: "https://flagcdn.com/lv.svg", dial_code: "+371" },
  { name: "Lebanon", flag: "https://flagcdn.com/lb.svg", dial_code: "+961" },
  { name: "Lesotho", flag: "https://flagcdn.com/ls.svg", dial_code: "+266" },
  { name: "Liberia", flag: "https://flagcdn.com/lr.svg", dial_code: "+231" },
  { name: "Libya", flag: "https://flagcdn.com/ly.svg", dial_code: "+218" },
  { name: "Liechtenstein", flag: "https://flagcdn.com/li.svg", dial_code: "+423" },
  { name: "Lithuania", flag: "https://flagcdn.com/lt.svg", dial_code: "+370" },
  { name: "Luxembourg", flag: "https://flagcdn.com/lu.svg", dial_code: "+352" },
  { name: "Macau", flag: "https://flagcdn.com/mo.svg", dial_code: "+853" },
  { name: "Macedonia", flag: "https://flagcdn.com/mk.svg", dial_code: "+389" },
  { name: "Madagascar", flag: "https://flagcdn.com/mg.svg", dial_code: "+261" },
  { name: "Malawi", flag: "https://flagcdn.com/mw.svg", dial_code: "+265" },
  { name: "Malaysia", flag: "https://flagcdn.com/my.svg", dial_code: "+60" },
  { name: "Maldives", flag: "https://flagcdn.com/mv.svg", dial_code: "+960" },
  { name: "Mali", flag: "https://flagcdn.com/ml.svg", dial_code: "+223" },
  { name: "Malta", flag: "https://flagcdn.com/mt.svg", dial_code: "+356" },
  { name: "Marshall Islands", flag: "https://flagcdn.com/mh.svg", dial_code: "+692" },
  { name: "Martinique", flag: "https://flagcdn.com/mq.svg", dial_code: "+596" },
  { name: "Mauritania", flag: "https://flagcdn.com/mr.svg", dial_code: "+222" },
  { name: "Mauritius", flag: "https://flagcdn.com/mu.svg", dial_code: "+230" },
  { name: "Mayotte", flag: "https://flagcdn.com/yt.svg", dial_code: "+262" },
  { name: "Mexico", flag: "https://flagcdn.com/mx.svg", dial_code: "+52" },
  { name: "Micronesia", flag: "https://flagcdn.com/fm.svg", dial_code: "+691" },
  { name: "Moldova", flag: "https://flagcdn.com/md.svg", dial_code: "+373" },
  { name: "Monaco", flag: "https://flagcdn.com/mc.svg", dial_code: "+377" },
  { name: "Mongolia", flag: "https://flagcdn.com/mn.svg", dial_code: "+976" },
  { name: "Montenegro", flag: "https://flagcdn.com/me.svg", dial_code: "+382" },
  { name: "Montserrat", flag: "https://flagcdn.com/ms.svg", dial_code: "+1664" },
  { name: "Morocco", flag: "https://flagcdn.com/ma.svg", dial_code: "+212" },
  { name: "Mozambique", flag: "https://flagcdn.com/mz.svg", dial_code: "+258" },
  { name: "Myanmar", flag: "https://flagcdn.com/mm.svg", dial_code: "+95" },
  { name: "Namibia", flag: "https://flagcdn.com/na.svg", dial_code: "+264" },
  { name: "Nauru", flag: "https://flagcdn.com/nr.svg", dial_code: "+674" },
  { name: "Nepal", flag: "https://flagcdn.com/np.svg", dial_code: "+977" },
  { name: "Netherlands", flag: "https://flagcdn.com/nl.svg", dial_code: "+31" },
  { name: "New Caledonia", flag: "https://flagcdn.com/nc.svg", dial_code: "+687" },
  { name: "New Zealand", flag: "https://flagcdn.com/nz.svg", dial_code: "+64" },
  { name: "Nicaragua", flag: "https://flagcdn.com/ni.svg", dial_code: "+505" },
  { name: "Niger", flag: "https://flagcdn.com/ne.svg", dial_code: "+227" },
  { name: "Nigeria", flag: "https://flagcdn.com/ng.svg", dial_code: "+234" },
  { name: "Niue", flag: "https://flagcdn.com/nu.svg", dial_code: "+683" },
  { name: "Norfolk Island", flag: "https://flagcdn.com/nf.svg", dial_code: "+672" },
  { name: "North Korea", flag: "https://flagcdn.com/kp.svg", dial_code: "+850" },
  { name: "Northern Mariana Islands", flag: "https://flagcdn.com/mp.svg", dial_code: "+1670" },
  { name: "Norway", flag: "https://flagcdn.com/no.svg", dial_code: "+47" },
  { name: "Oman", flag: "https://flagcdn.com/om.svg", dial_code: "+968" },
  { name: "Pakistan", flag: "https://flagcdn.com/pk.svg", dial_code: "+92" },
  { name: "Palau", flag: "https://flagcdn.com/pw.svg", dial_code: "+680" },
  { name: "Palestine", flag: "https://flagcdn.com/ps.svg", dial_code: "+970" },
  { name: "Panama", flag: "https://flagcdn.com/pa.svg", dial_code: "+507" },
  { name: "Papua New Guinea", flag: "https://flagcdn.com/pg.svg", dial_code: "+675" },
  { name: "Paraguay", flag: "https://flagcdn.com/py.svg", dial_code: "+595" },
  { name: "Peru", flag: "https://flagcdn.com/pe.svg", dial_code: "+51" },
  { name: "Philippines", flag: "https://flagcdn.com/ph.svg", dial_code: "+63" },
  { name: "Pitcairn", flag: "https://flagcdn.com/pn.svg", dial_code: "+870" },
  { name: "Poland", flag: "https://flagcdn.com/pl.svg", dial_code: "+48" },
  { name: "Portugal", flag: "https://flagcdn.com/pt.svg", dial_code: "+351" },
  { name: "Puerto Rico", flag: "https://flagcdn.com/pr.svg", dial_code: "+1" },
  { name: "Qatar", flag: "https://flagcdn.com/qa.svg", dial_code: "+974" },
  { name: "Republic of the Congo", flag: "https://flagcdn.com/cg.svg", dial_code: "+242" },
  { name: "Reunion", flag: "https://flagcdn.com/re.svg", dial_code: "+262" },
  { name: "Romania", flag: "https://flagcdn.com/ro.svg", dial_code: "+40" },
  { name: "Russia", flag: "https://flagcdn.com/ru.svg", dial_code: "+7" },
  { name: "Rwanda", flag: "https://flagcdn.com/rw.svg", dial_code: "+250" },
  { name: "Saint Barthelemy", flag: "https://flagcdn.com/bl.svg", dial_code: "+590" },
  { name: "Saint Helena", flag: "https://flagcdn.com/sh.svg", dial_code: "+290" },
  { name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/kn.svg", dial_code: "+1869" },
  { name: "Saint Lucia", flag: "https://flagcdn.com/lc.svg", dial_code: "+1758" },
  { name: "Saint Martin", flag: "https://flagcdn.com/mf.svg", dial_code: "+590" },
  { name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/pm.svg", dial_code: "+508" },
  { name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/vc.svg", dial_code: "+1784" },
  { name: "Samoa", flag: "https://flagcdn.com/ws.svg", dial_code: "+685" },
  { name: "San Marino", flag: "https://flagcdn.com/sm.svg", dial_code: "+378" },
  { name: "Sao Tome and Principe", flag: "https://flagcdn.com/st.svg", dial_code: "+239" },
  { name: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg", dial_code: "+966" },
  { name: "Senegal", flag: "https://flagcdn.com/sn.svg", dial_code: "+221" },
  { name: "Serbia", flag: "https://flagcdn.com/rs.svg", dial_code: "+381" },
  { name: "Seychelles", flag: "https://flagcdn.com/sc.svg", dial_code: "+248" },
  { name: "Sierra Leone", flag: "https://flagcdn.com/sl.svg", dial_code: "+232" },
  { name: "Singapore", flag: "https://flagcdn.com/sg.svg", dial_code: "+65" },
  { name: "Sint Maarten", flag: "https://flagcdn.com/sx.svg", dial_code: "+1721" },
  { name: "Slovakia", flag: "https://flagcdn.com/sk.svg", dial_code: "+421" },
  { name: "Slovenia", flag: "https://flagcdn.com/si.svg", dial_code: "+386" },
  { name: "Solomon Islands", flag: "https://flagcdn.com/sb.svg", dial_code: "+677" },
  { name: "Somalia", flag: "https://flagcdn.com/so.svg", dial_code: "+252" },
  { name: "South Africa", flag: "https://flagcdn.com/za.svg", dial_code: "+27" },
  { name: "South Korea", flag: "https://flagcdn.com/kr.svg", dial_code: "+82" },
  { name: "South Sudan", flag: "https://flagcdn.com/ss.svg", dial_code: "+211" },
  { name: "Spain", flag: "https://flagcdn.com/es.svg", dial_code: "+34" },
  { name: "Sri Lanka", flag: "https://flagcdn.com/lk.svg", dial_code: "+94" },
  { name: "Sudan", flag: "https://flagcdn.com/sd.svg", dial_code: "+249" },
  { name: "Suriname", flag: "https://flagcdn.com/sr.svg", dial_code: "+597" },
  { name: "Svalbard and Jan Mayen", flag: "https://flagcdn.com/sj.svg", dial_code: "+47" },
  { name: "Swaziland", flag: "https://flagcdn.com/sz.svg", dial_code: "+268" },
  { name: "Sweden", flag: "https://flagcdn.com/se.svg", dial_code: "+46" },
  { name: "Switzerland", flag: "https://flagcdn.com/ch.svg", dial_code: "+41" },
  { name: "Syria", flag: "https://flagcdn.com/sy.svg", dial_code: "+963" },
  { name: "Taiwan", flag: "https://flagcdn.com/tw.svg", dial_code: "+886" },
  { name: "Tajikistan", flag: "https://flagcdn.com/tj.svg", dial_code: "+992" },
  { name: "Tanzania", flag: "https://flagcdn.com/tz.svg", dial_code: "+255" },
  { name: "Thailand", flag: "https://flagcdn.com/th.svg", dial_code: "+66" },
  { name: "Timor-Leste", flag: "https://flagcdn.com/tl.svg", dial_code: "+670" },
  { name: "Togo", flag: "https://flagcdn.com/tg.svg", dial_code: "+228" },
  { name: "Tokelau", flag: "https://flagcdn.com/tk.svg", dial_code: "+690" },
  { name: "Tonga", flag: "https://flagcdn.com/to.svg", dial_code: "+676" },
  { name: "Trinidad and Tobago", flag: "https://flagcdn.com/tt.svg", dial_code: "+1868" },
  { name: "Tunisia", flag: "https://flagcdn.com/tn.svg", dial_code: "+216" },
  { name: "Turkey", flag: "https://flagcdn.com/tr.svg", dial_code: "+90" },
  { name: "Turkmenistan", flag: "https://flagcdn.com/tm.svg", dial_code: "+993" },
  { name: "Turks and Caicos Islands", flag: "https://flagcdn.com/tc.svg", dial_code: "+1649" },
  { name: "Tuvalu", flag: "https://flagcdn.com/tv.svg", dial_code: "+688" },
  { name: "Uganda", flag: "https://flagcdn.com/ug.svg", dial_code: "+256" },
  { name: "Ukraine", flag: "https://flagcdn.com/ua.svg", dial_code: "+380" },
  { name: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg", dial_code: "+971" },
  { name: "United Kingdom", flag: "https://flagcdn.com/gb.svg", dial_code: "+44" },
  { name: "United States", flag: "https://flagcdn.com/us.svg", dial_code: "+1" },
  { name: "Uruguay", flag: "https://flagcdn.com/uy.svg", dial_code: "+598" },
  { name: "Uzbekistan", flag: "https://flagcdn.com/uz.svg", dial_code: "+998" },
  { name: "Vanuatu", flag: "https://flagcdn.com/vu.svg", dial_code: "+678" },
  { name: "Vatican City", flag: "https://flagcdn.com/va.svg", dial_code: "+39" },
  { name: "Venezuela", flag: "https://flagcdn.com/ve.svg", dial_code: "+58" },
  { name: "Vietnam", flag: "https://flagcdn.com/vn.svg", dial_code: "+84" },
  { name: "Wallis and Futuna", flag: "https://flagcdn.com/wf.svg", dial_code: "+681" },
  { name: "Western Sahara", flag: "https://flagcdn.com/eh.svg", dial_code: "+212" },
  { name: "Yemen", flag: "https://flagcdn.com/ye.svg", dial_code: "+967" },
  { name: "Zambia", flag: "https://flagcdn.com/zm.svg", dial_code: "+260" },
  { name: "Zimbabwe", flag: "https://flagcdn.com/zw.svg", dial_code: "+263" }
]