// Helper component for styled headings
const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <h2 className="text-3xl font-bold text-gray-800 mt-12 mb-4">{children}</h2>
);

const SubTitle = ({ children }: { children: React.ReactNode }) => (
  <h3 className="text-2xl font-bold text-gray-700 mt-8 mb-3">{children}</h3>
);

export default function PrivacyPolicyPage() {
  return (
    <>
      {/* --- Hero Section --- */}
      <section
        className="relative h-[50vh] flex items-center justify-center text-white"
        style={{
          backgroundImage: "linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('/policy.png')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <h1 className="text-5xl md:text-6xl font-bold z-10">Privacy Policy</h1>
      </section>

      {/* --- Main Content --- */}
      <section className="bg-white py-20">
        <div className="container mx-auto px-6 max-w-4xl text-gray-700 leading-relaxed">
          <p className="mb-6">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

          <SectionTitle>Interpretation and Definitions</SectionTitle>
          <SubTitle>Interpretation</SubTitle>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

          <SubTitle>Definitions</SubTitle>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside space-y-3 mt-4">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to BizVibez Properties, 602 Bays Water Tower, Business Bay Dubai United Arab Emirates.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: United Arab Emirates</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to BizVibez Properties, accessible from your domain.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <SectionTitle>Collecting and Using Your Personal Data</SectionTitle>
          <SubTitle>Types of Data Collected</SubTitle>
          <p><strong>Personal Data</strong></p>
          <p className="mt-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, Phone number, and Usage Data.</p>
          
          <p className="mt-6"><strong>Usage Data</strong></p>
          <p className="mt-2">Usage Data is collected automatically when using the Service. It may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data.</p>

          <SubTitle>Tracking Technologies and Cookies</SubTitle>
          <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>

          <SectionTitle>Use of Your Personal Data</SectionTitle>
          <p>The Company may use Personal Data for the following purposes:</p>
           <ul className="list-disc list-inside space-y-3 mt-4">
              <li>To provide and maintain our Service.</li>
              <li>To manage Your Account.</li>
              <li>For the performance of a contract.</li>
              <li>To contact You with updates or informative communications.</li>
              <li>To provide You with news, special offers and general information.</li>
              <li>To manage Your requests.</li>
          </ul>
          
          <SectionTitle>Links to Other Websites</SectionTitle>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

          <SectionTitle>Changes to this Privacy Policy</SectionTitle>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>

          <SectionTitle>Contact Us</SectionTitle>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
           <ul className="list-disc list-inside space-y-3 mt-4">
              <li><strong>By email:</strong> info@bizvibezproperties.com</li>
              <li><strong>By visiting this page on our website:</strong> https://bizvibezproperties.com/contact/</li>
              <li><strong>By phone number:</strong> +971 54 201 9999</li>
          </ul>
        </div>
      </section>
    </>
  );
}

